#SPDX-License-Identifier: MIT-0
---
# tasks file for kibana

- name: Ensure destination directory exists
  file:
    path: "{{ source_file_kibana }}"
    state: directory

- name: Download  Kibana
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-9.0.2-amd64.deb
    dest: "{{source_file_kibana}}/kibana.deb"

- name: Install Kibana
  apt:
    deb: "{{source_file_kibana}}/kibana.deb"

- name: Enable Kibana
  systemd_service:
    daemon_reload: true
    name: kibana.service
    state: started
    enabled: true

- name: Configure kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    mode: "0755"

- name: Restart Kibana
  systemd_service:
    name: kibana.service
    state: started
