#SPDX-License-Identifier: MIT-0
---
# tasks file for controller
- name: Instaling ncessary packages
  apt:
    name:
      - containerd
      - containernetworking-plugins
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gpg
    state: present
    update_cache: yes

- name: Ensure /etc/apt/keyrings exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes GPG key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /tmp/kubernetes-release.key

- name: Add Kubernetes apt key
  command: apt-key add /tmp/kubernetes-release.key

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    filename: kubernetes
    state: present

- name: Install kubelet, kubeadm, kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Install kubeadm, kubelet, kubectl
  apt:
    name:
      - kubeadm
      - kubelet
      - kubectl

- name: Enable and start kubelet
  become: yes
  systemd:
    name: kubelet
    enabled: yes
    state: started
