#SPDX-License-Identifier: MIT-0
---
# tasks file for elasticSearch

- name: Ensure destination directory exists
  file:
    path: "{{ source_file }}"
    state: directory

- name: Download ElasticSearch 
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-9.0.2-amd64.deb
    dest: "{{source_file}}/elasticsearch.deb"

- name: Install ElasticSearch
  apt:
    deb: "{{source_file}}/elasticsearch.deb"

- name: reload daemon
  command: >
      /bin/systemctl daemon-reload

- name: Delete keystroke
  command: >
    /usr/share/elasticsearch/bin/elasticsearch-keystore remove xpack.security.http.ssl.keystore.secure_password
  ignore_errors: true

- name: Delete keystroke
  command: >
    /usr/share/elasticsearch/bin/elasticsearch-keystore remove xpack.security.transport.ssl.keystore.secure_password
  ignore_errors: true

- name: Delete keystroke
  command: >
    /usr/share/elasticsearch/bin/elasticsearch-keystore remove xpack.security.transport.ssl.truststore.secure_password
  ignore_errors: true


- name: Create Elasticsearch data directory
  ansible.builtin.file:
    path: /usr/share/elasticsearch/data
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0755'

- name: Create Elasticsearch logs directory
  ansible.builtin.file:
    path: /usr/share/elasticsearch/logs/
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0755'

- name: Enable elasticsearch
  systemd_service:
    daemon_reload: true
    name: elasticsearch.service
    enabled: true

- name: Configure elasticsearch header
  template:
    src: elasticsearch-head.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: "0755"
  when: "'tag_Name_elastic_header_0' in group_names"

- name: Configure elasticsearch node
  template:
    src: elasticsearch-node.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: "0755"
  when: "'tag_Name_elastic_node' in group_names"

- name: Start Elasticsearch
  systemd_service:
    name: elasticsearch.service
    state: started
